### ISSUE TITLE
Establish front-end architecture

### ISSUE THREAD

**Issue by nerdstein** [CivicActions/agile-ms#2]
In "docroot" directory... 

Task runner, bootstrap, and angular

**Comment by nerdstein** [comment]
Please update the readme.md with findings

**Comment by nerdstein** [comment]
Expecting a pull request with the code into a new "docroot" folder.

Also expecting instructions for using the task runner on readme.md

**Comment by aschmoe** [comment]
@ethanteague and I have decided on a Gulp based task runner, using angular as the front end js framework.  Ethan is setting up the repo, while I compile some tools to take in the raw json file from the /data directory

**Comment by nerdstein** [comment]
Still waiting on Angular from @aschmoe

**Comment by nerdstein** [comment]
Added Gulp to the tech stack: https://github.com/CivicActions/agile-ms/pull/11

**Comment by nerdstein** [comment]
PR from Alex for Angular: https://github.com/CivicActions/agile-ms/pull/12

**Comment by nerdstein** [comment]
PR from Ethan on Bootstrap and Gulp: https://github.com/CivicActions/agile-ms/pull/9

**Comment by nerdstein** [comment]
Work completed
