### ISSUE TITLE
Embed data source in repo

### ISSUE THREAD

**Issue by nerdstein** [CivicActions/agile-ms#3]
Create data directory

Place static JSON 

Create environment to hardcode JSON path/endpoint, e.g. "agilems-data.civicactions.com/data.json"

**Comment by nerdstein** [comment]
Rob Reid created a groomed JSON file from the state's furnished CSV posted on their site, here: https://app.smartsheet.com/b/publish?EQBCT=7c93b5eee3014eddba002054da5a69fd

JSON file:
https://github.com/RobertLRead/chhs-geojson/blob/gh-pages/MS%20ITS%20RFP%203717-Vendor%20Challenge%20Dataset%20FINAL.json

Rob converted the file with http://kinlane.github.io/csv-converter/ and did some manual cleanup.

**Comment by nerdstein** [comment]
For MVP - we might be able to use the raw output from Github from Rob's JSON - https://raw.githubusercontent.com/RobertLRead/chhs-geojson/gh-pages/MS%20ITS%20RFP%203717-Vendor%20Challenge%20Dataset%20FINAL.json

**Comment by nerdstein** [comment]
I would recommend we move this JSON into our repo and just use the RAW link as the endpoint.

I need to inquire if we can make the repo public or private. If the endpoint is not public, we might need the cloud to serve up the endpoint

**Comment by nerdstein** [comment]
Per rob - we can and should make the repo public. I'm working on that now and we can use the endpoint

**Comment by Pythagory** [comment]
Data file added in this commit: https://github.com/CivicActions/agile-ms/commit/6d9f7ef1376b4fe497957cf5de185115e01e9dd3

**Comment by nerdstein** [comment]
Raw link found here --- https://raw.githubusercontent.com/CivicActions/agile-ms/master/data/MS%20ITS%20RFP%203717-Vendor%20Challenge%20Dataset%20FINAL.json

**Comment by nerdstein** [comment]
That would be our endpoint, @ethanteague @aschmoe @Pythagory

**Comment by aschmoe** [comment]
@nerdstein the Angular app (when its not blowing it), is using that as its "API"
